In [1]:
# 1. Create an array and traverse. 
from array import *

my_array = array('i',[1,2,3,4,5])

for i in my_array:
    print(i)

1
2
3
4
5


In [6]:
# 2. Access individual elements through indexes

print('first element: ', my_array[0])
print('THird element: ', my_array[3])


first element:  1
THird element:  4


In [10]:
# 3. Append any value to the array using append() method

my_array.append(6)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6, 10, 11, 12, 6])


In [11]:
# 4. Insert value in an array using insert() method

my_array.insert(0, 11)
print(my_array)


array('i', [11, 11, 1, 2, 3, 4, 5, 6, 10, 11, 12, 6])


In [13]:
# 5. Extend python array using extend() method


my_array = array('i',[1,2,3,4,5,6])
my_array1 = array('i', [10,11,12])
my_array.extend(my_array1)
print(my_array)




array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12])


In [15]:

# 6. Add items from list into array using fromlist() method

tempList = [20,21,22]
my_array.fromlist(tempList)
print(my_array)



array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22, 20, 21, 22])


In [16]:
# 7. Remove any array element using remove() method

my_array.remove(11)
print(my_array)


array('i', [1, 2, 3, 4, 5, 6, 10, 12, 20, 21, 22, 20, 21, 22])


In [20]:
# 8. Remove last array element using pop() method
#remove last element

my_array.pop()
print(my_array)




array('i', [1, 2, 3, 4, 5, 6, 10, 12, 20, 21, 22, 20, 21])


In [23]:
# 9. Fetch any element through its index using index() method
#find the index of value in a list
print(my_array.index(21))



9
array('i', [1, 2, 3, 4, 5, 6, 10, 12, 20, 21, 22, 20, 21])


In [24]:
# 10. Reverse a python array using reverse() method
my_array.reverse()
print(my_array)



array('i', [21, 20, 22, 21, 20, 12, 10, 6, 5, 4, 3, 2, 1])


In [26]:
# 11. Get array buffer information through buffer_info() method


print(my_array.buffer_info())


(2454176560304, 13)


In [30]:
# 12. Check for number of occurrences of an element using count() method
my_array.append(11)
print(my_array.count(11))



2


In [33]:
# 13. Convert array to string using tostring() method

strTemp = my_array.tobytes()
print(strTemp)

ints = array('i')
ints.frombytes(strTemp)
print(ints)


b'\x15\x00\x00\x00\x14\x00\x00\x00\x16\x00\x00\x00\x15\x00\x00\x00\x14\x00\x00\x00\x0c\x00\x00\x00\n\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0b\x00\x00\x00\x0b\x00\x00\x00'
array('i', [21, 20, 22, 21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 11, 11])


In [34]:
# 14. Convert array to a python list with same elements using tolist() method

print(my_array.tolist())


[21, 20, 22, 21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 11, 11]


In [39]:
import array

# Create the initial array of characters
char_array = array.array('u', 'Hello')

# Convert string to characters and extend the array
char_array.fromunicode(' World')

# Convert char array back to a string for display
result = char_array.tounicode()

print(result)


Hello World


In [43]:
# 16. Slice Elements from an array

my_array[1:4]
my_array[2:]
my_array[:4]
my_array[:]



array('i', [21, 20, 22, 21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 11, 11])

In [44]:
import numpy as np

twoDarray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])

print(twoDarray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [46]:
#insertion into two dimesnional array
# types of insertion
# 1)additional column
# 2)additional row
#column insert = 1
newTwoDArray = np.insert(twoDarray, 0, [1,2,3,4], axis = 1)

print(twoDarray)
print(newTwoDArray)



[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [47]:
#row insert 0
newTwoDArray = np.insert(twoDarray, 0, [1,2,3,4], axis = 0)

print(twoDarray)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [48]:
#row insert at 2nd index
newTwoDArray = np.insert(twoDarray, 2, [1,2,3,4], axis = 0)

print(twoDarray)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11 15 10  6]
 [10 14 11  5]
 [ 1  2  3  4]
 [12 17 12  8]
 [15 18 14  9]]


In [49]:
#append method at end of row
newTwoDArray = np.append(twoDarray, [[1,2,3,4]], axis = 0 )

print(twoDarray)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [4]:
#accessing the elements in two dimesional array
import numpy as np

twoDarray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])

print(twoDarray)

def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('Incorrect index')
    else:
        print(array[rowIndex][colIndex])


accessElements(twoDarray, 1, 2)        
accessElements(twoDarray, 2, 3)        



[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
8


In [9]:
#traversing two dimension array
import numpy as np

twoDarray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDarray)
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
        

traverseTDArray(twoDarray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [3]:
#searching two dimenional array
#Linear search
import numpy as np

twoDarray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDarray)


def searchTDArray(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located at index: '+str(i)+" "+str(j)
    return 'The element is not found'

print(searchTDArray(twoDarray, 14))
# print(searchTDArray(twoDarray, 144))

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
The value is located at index: 1 1
The element is not found


In [4]:
# deletion in 2D Array
import numpy as np

twoDarray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDarray)

#delete the row of the array
deleteArray = np.delete(twoDarray, 0, axis = 0)
print(deleteArray)
#delete the column of the array
deleteArray = np.delete(twoDarray, 0, axis = 1)
print(deleteArray)
#delete the column of the array
deleteArray = np.delete(twoDarray, 1, axis = 1)
print(deleteArray)
#time complexity o(mn)
#space complexity o(mn)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[15 10  6]
 [14 11  5]
 [17 12  8]
 [18 14  9]]
[[11 10  6]
 [10 11  5]
 [12 12  8]
 [15 14  9]]
